version: '3.8'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FLASK_DEBUG=True
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
