services:
  - type: web
    name: bhv-demo
    env: python
    region: oregon
    plan: free
    branch: feature/add-render-deployment
    buildCommand: "./build.sh"
    startCommand: "gunicorn bhv.app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production